trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'your-docker-repo/streamlit-llm-app'
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Dev-PlatformsPP'
    appName: 'QueryCrushers-App'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.8'