AZURE_OPENAI_KEY = "Fd5fRGLOIU5H73FMJvHH4el0P9v8X0i0WEDxYTr0SzPvsmKY2p8iJQQJ99BEACI8hq2XJ3w3AAAAACOGX3e4"
AZURE_OPENAI_ENDPOINT = "https://hackathonquery4412999835.cognitiveservices.azure.com/"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"  # ou a versão usada no teu serviço
AZURE_OPENAI_DEPLOYMENT = "gpt-35-turbo-Playground"

DB_HOST = "querycrushers-webapp-server2.postgres.database.azure.com"
DB_NAME = "querycrushersdatabase"
DB_USER = "querycrushers"
DB_PASSWORD = "#x6m4K%eF2!AjM7"