# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - QueryCrushers-WebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://querycrushersacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ce3d30c599954408bc9436d2709ce706 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f7844895ca6041369da1e6ed5c18b690 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: querycrushersacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ce3d30c599954408bc9436d2709ce706 }}/latest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'QueryCrushers-WebApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1ce0eeaa778f4d8da2c0a40ac21394d2 }}
        images: 'querycrushersacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ce3d30c599954408bc9436d2709ce706 }}/latest:${{ github.sha }}'